# Generated by Django 3.0 on 2020-10-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TamañoBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(help_text='Ej. Pequeña, Mediana, Grande, etc.', max_length=50, verbose_name='Tamaño de bedido')),
                ('descripcion', models.CharField(help_text='Ej. 360 ml, 600 ml, 1 litro, etc.', max_length=10, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tamaño de bebida',
                'verbose_name_plural': 'Tamaños de bebidas',
                'db_table': 'tamaño_bebida',
                'unique_together': {('tamaño', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Refresco de tamarindo, refresco de jamaica, coca-cola, seven up, etc.', max_length=50, verbose_name='Nombre de la bebida')),
                ('imagen', models.ImageField(blank=True, max_length=255, upload_to='img/%Y/%m/%d')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.TamañoBebida')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'db_table': 'bebida',
                'unique_together': {('nombre', 'tamaño')},
            },
        ),
    ]
