# Generated by Django 3.0 on 2020-10-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlatillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej. Desayuno, Almuerzo, Cena, etc.', max_length=50, verbose_name='Tipo de platillo')),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
            ],
            options={
                'verbose_name': 'Tipo de platillo',
                'verbose_name_plural': 'Tipos de platillos',
                'db_table': 'tipo_platillo',
                'unique_together': {('tipo',)},
            },
        ),
    ]
