# Generated by Django 3.0 on 2020-10-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platillos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del platillo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platillos.TipoPlatillo')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'db_table': 'platillo',
                'unique_together': {('nombre',)},
            },
        ),
    ]
