# Generated by Django 3.0 on 2020-10-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingresar solo los nombres', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Ingresar solo los apellidos', max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(help_text='Ejemplo: 01/01/1991', verbose_name='Fecha de nacimiento')),
                ('nombre_facturacion', models.CharField(help_text='Nombre que saldrá en la factura', max_length=50, verbose_name='Nombre de facturación')),
                ('nit', models.CharField(help_text='NIT que aparecerá en la factura', max_length=11, verbose_name='NIT')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='NumeroTelefonico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Celular'), ('P', 'Particular'), ('L', 'Laboral'), ('R', 'Residencial'), ('O', 'Otro')], default='C', help_text='Elegir el tipo de número telefónico. Ej. Celular', max_length=1, verbose_name='Tipo número telefónico')),
                ('numero', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Número telefónico de cliente',
                'verbose_name_plural': 'Agenda telefónica de clientes',
                'db_table': 'telefonosclientes',
                'unique_together': {('numero',)},
            },
        ),
    ]
