# Generated by Django 3.0 on 2020-10-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0001_initial'),
        ('clientes', '0003_auto_20201014_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direcciones.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre',
            field=models.CharField(help_text='Nombre de referencia de la dirección Ej. Hogar#1.', max_length=50, verbose_name='Nombre de la dirección'),
        ),
    ]
