# Generated by Django 3.0 on 2020-10-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20201021_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='avenida',
            field=models.CharField(blank=True, help_text='Solo ingresar el número de avenida', max_length=2, verbose_name='Avenida'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='barrio',
            field=models.CharField(blank=True, help_text='Nombre del barrio', max_length=30, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, help_text='Solo ingresar el número de calle', max_length=2, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, help_text='Nombre de la colonia', max_length=30, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='lote',
            field=models.CharField(blank=True, help_text='Solo ingresar el número de lote', max_length=3, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='manzana',
            field=models.CharField(blank=True, max_length=2, verbose_name='Manzana'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero_casa',
            field=models.CharField(blank=True, help_text='Ej. 4-10, 10-52, etc.', max_length=5, verbose_name='Número de Casa'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='residencial',
            field=models.CharField(blank=True, help_text='Nombre del residencial', max_length=30, verbose_name='Residencial'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='zona',
            field=models.CharField(blank=True, help_text='Nombre del barrio', max_length=30, verbose_name='Zona'),
        ),
    ]
