# Generated by Django 3.0 on 2020-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_cliente_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, help_text='Constraseña que utilizará para ingresar al sistema', max_length=50, verbose_name='Contraseña'),
        ),
    ]
